# arxifter configuration

[server]
# header_origin has to be set to the actual server spec where the arxifter gets deployed;
# (if arxifter is deployed on https://example.net it should be set to it);
# the guests and query requests check it.
# if it is set as an empty string, the checking is not performed.
# here the 8000 port is according to the expected docker/podman deployment
header_origin = "http://localhost:8000"
# the port on which the web server listens;
# (docker/podman can remap it to another port at the host)
port = 5000
# when arxifter is served via docker/podman, it has to listen on the 0.0.0.0 interface.
# a serving w/o that, but still behind a reverse proxy, asks for "127.0.0.1" then;
address = "0.0.0.0"
# whether the server is covered by a reverse proxy server;
# static files are assumed to be served by that proxy;
behind_proxy = false

[access]
# access rules based on client IP address:
# the allow-list is checked first, making contained IP addresses allowed;
# if an IP address is not contained there,
# it is disallowed if the default way is not allowing
# or when the IP address is contained in the block-list;
# if nothing of that happens, the IP address is allowed;
# the access lists are reread if the respective files get modified;
# the rules can differ for regular users vs. guest users:
# option whether regular users are allowed by default
user_default_allow = true
# file with allowed IP-address ranges for regular users;
# empty path means that no such rules are formed;
user_allow_list = "../conf/access/users_allow.list"
# file with blocked IP-address ranges for regular users;
# empty path means that no such rules are formed;
user_block_list = "../conf/access/users_block.list"
# whether the disallowed IP address is stated to regular users
# when it happens that user IP address is not allowed;
user_show_blocked_ip = true
# option whether guest users are allowed by default
guest_default_allow = true
# file with allowed IP-address ranges for guest users;
# empty path means that no such rules are formed;
guest_allow_list = "../conf/access/guests_allow.list"
# file with blocked IP-address ranges for guest users;
# empty path means that no such rules are formed;
guest_block_list = "../conf/access/guests_block.list"
# whether the disallowed IP address is stated to guest users
# when it happens that user IP address is not allowed;
guest_show_blocked_ip = true

[view]
# the path at which the arxifter web is served;
# set it to "" if arxifter is served at the "/" path
path_prefix = "/biorxiv"
# the page shown to users has two versions:
# with common JS libs served from CDN vs. locally
# main_page = "../view/page_local.html"
main_page = "../view/page_cdn.html"
# where the statically served files are located
static_dir = "../view/static/"

[backlink]
# to be set according to actual deployments;
# the top-left link: it can be customized;
name = "arχifter"
link = "https://arxifter.quadet.com"
title = "to arχifter home page"

[notices]
# the text at the top of the user-popup
note_users = "about.txt"
# whether the note_users file should be rendered as html;
# if not, it is rendered as plain text
note_users_html = false

[ui]
# a technical part that can be left unchanged;
# for cookie that keeps user id if users ask for it
user_id = "arxifter.userid"
# how many days that cookie should be kept;
# it gets auto-renewed if user visits arxifter meanwhile
retain_user = 30
# name prefix for items stored at browser local storage
storage_prefix = "arxifter.biorxiv"
# how many sifts can get stored in browser local storage;
# the sifts are stored by default, but users can disallow it;
# since browsers have a limited capacity for data storage,
# this value should not be set too large;
recall_sifts = 20

[feeds]
# deployments can be used for a subset of feeds only;
# and combined subjects can be specified for feeds too;
subjects = "subjects.txt"
default_subject = "cell_biology"
# to allow users to make queries with subject combinations
# differing from the listed ones in the "subjects" file;
# it still has to be with subjects listed there at first;
allow_combinations = true

[data]
# where the feeds and the data based on them are stored;
storage_dir = "../feed/"
# whether past stored feed data should be removed;
pruning = true
# how long the feeds should be retained;
# 'kept_days' value is used for the RSS-based 'perm' data
# and for the 'span' part of the JSON-API data;
# (this value is used only when 'pruning' is set to true)
kept_days = 7
# the depo part of ingested data
# how many days are used for the 'last-days' siftings;
depo_depth = 30
# how many days are taken within each incremental depo-wise data ingest;
depo_renew = 2
# how many days are kept within the 'depo' subject-wise subdirectories;
# (this value is used only when 'pruning' is set to true)
depo_kept_days = 50

[libs]
# directory with a version of hnswlib that has knn searches
# with support for returning unique docs;
# arxifter uses a patched hnswlib for sentence-wise searches;
hnswlib = "../libs/hnswlib/"

[embed]
# models from HF are expected to be stored at "hub" subdirectory
# of the directory set to the "models_base_dir" key
models_base_dir = "../mods/"
# model for dense encoders
# (in the way it is taken by the fastembed library);
# if the "dense_embed_model" is not within the models recognized
# by the fastembed library, the respective HF directory
# has to contain info.toml file with model specification;
dense_embed_model = "BAAI/bge-base-en-v1.5"
dense_embed_dim = 768
# dense_embed_model = "local/neuml-pubmedbert-base-embeddings-fp16"
# dense_embed_dim = 768
# model for static encoders
# (in the way it is taken by the model2vec library)
static_embed_model = "NeuML/pubmedbert-base-embeddings-8M"
static_embed_dim = 256

[sifting]
# presifting part done by the used dense embedding model
pick_count_dense = 5
# presifting part done by the used static embedding model
pick_count_static = 5
# the maximal count of articles that LLM ought to provide
answer_max_count = 5

[prompts]
# the prompt parts that are used for LLM querying;
# prompt lines that start with ';;' (two semicolons) are taken as comments
main_part = "prompts/main.txt"
query_part = "prompts/query.txt"
# put in the middle if the used LLM has to be reminded of being honest
asking_honest = "prompts/honest.txt"
# put to start if the used LLM has to be forced to reasoning
asking_think = "prompts/think.txt"
# put to end if the used LLM has to be forced to CoT
asking_cot = "prompts/cot.txt"

[llms]
# setting the max count of tokens that the remote LLM can do;
# it sums the reasoning and the actual-output tokens;
# (that if the used remote system supports this part of OpenAI API);
# setting "max_tokens" to 0 means that there is no cap set up;
# max_tokens = 16384
max_tokens = 0
# most of the usable LLMs answer within 1 min,
# thus timeout of 120 seconds is safe for them;
# but seed-oss-36b is quite slow (1 to 3 mins to answer),
# thus its use asks for a longer timeout, some 240 secs;
# and qwen3.6-27b asks for such a longer timeout too;
timeout = 120
# LLM inference API end point for OpenAI compatible services;
# empty "base_url" means that OpenAI is used;
# * "model_name" model used by the inferring LLM;
# * "ask_honest" for stressing to admit situations when no article
#   fits the user's query, as some models hesitate to do it;
# * "asking_form" is "responses" or "chat-completions"

# Runpod:
# base_url = "path:../../ext/runpod/pods/arxifter/nemotron-3-nano-fp8-kv-fp8/001/pod.url"
# asking_form = "chat-completions"
# model_name = "nvidia/nemotron-3-nano-30b-a3b-fp8-kv-fp8"
# ask_honest = false
# base_url = "path:../../ext/runpod/pods/arxifter/laguna-xs-2.1-fp8-kv-fp8/001/pod.url"
# asking_form = "chat-completions"
# model_name = "poolside/laguna-xs-2.1-fp8-kv-fp8|think"
# ask_honest = true

# NVIDIA:
# * inference via this provider is free of charge,
#   but it is for testing purposes only;
# base_url = "https://integrate.api.nvidia.com/v1"
# asking_form = "chat-completions"
# model_name = "openai/gpt-oss-20b"
# ask_honest = false
# model_name = "nvidia/nemotron-3-nano-30b-a3b"
# ask_honest = false

# OpenRouter:
base_url = "https://openrouter.ai/api/v1"
asking_form = "chat-completions"
# model_name = "openai/gpt-oss-20b"
# ask_honest = false
model_name = "nvidia/nemotron-3-nano-30b-a3b"
ask_honest = false
# model_name = "google/gemma-4-31b-it|cot"
# ask_honest = true
# model_name = "qwen/qwen3.6-35b-a3b"
# ask_honest = true
# model_name = "cohere/north-mini-code:free"
# ask_honest = false
# model_name = "poolside/laguna-xs-2.1|think"
# ask_honest = true
# model_name = "meta/muse-glimmer-30b"
# ask_honest = false

# Fireworks AI:
# base_url = "https://api.fireworks.ai/inference/v1"
# asking_form = "responses"
# model_name = "fireworks/gpt-oss-20b"
# ask_honest = false

# Nebius:
# base_url = "https://api.tokenfactory.nebius.com/v1/"
# asking_form = "chat-completions"
# model_name = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B"
# ask_honest = false

[users]
# if a deployment is to be w/o allowing guests,
# the "with_guest" value has to be set to false
with_guest = true
# session span (in hours) of guest users
guest_span = 24
# where ids of regular and guest users are stored;
# users are set by ids only (i.e. not by name/password pairs);
regular_users = "../keys/users.list"
guest_ids = "../keys/guest/"

[keys]
# locations of LLM api keys;
regular_users = "../keys/users/"
guest_user = "../keys/guest.key"

[mocking]
# for development purposes
answers_dir = "../conf/mocking/"
mocking_delay = 4
to_mock = false

[debugging]
# for testing purposes
query_sifting = false
feed_ingest = false
