# arxifter configuration

[server]
# header_origin has to be set to the actual server spec where the arxifter gets deployed;
# (if arxifter is deployed on https://example.net it should be set to it);
# the guests and query requests check it.
# if it is set as an empty string, the checking is not performed.
# here the 8000 port is according to the expected docker/podman deployment
header_origin = "http://localhost:8000"
# the port on which the web server listens;
# (docker/podman can remap it to another port at the host)
port = 5000
# when arxifter is served via docker/podman, it has to listen on the 0.0.0.0 interface.
# a serving w/o that, but still behind a reverse proxy, asks for "127.0.0.1" then;
address = "0.0.0.0"
# whether the server is covered by a reverse proxy server;
# static files are assumed to be served by that proxy;
behind_proxy = false

[access]
# access rules based on client IP address:
# the allow-list is checked first, making contained IP addresses allowed;
# if an IP address is not contained there,
# it is disallowed if the default way is not allowing
# or when the IP address is contained in the block-list;
# if nothing of that happens, the IP address is allowed;
# the access lists are reread if the respective files get modified;
# the rules can differ for regular users vs. guest users:
# option whether regular users are allowed by default
user_default_allow = true
# file with allowed IP-address ranges for regular users;
# empty path means that no such rules are formed;
user_allow_list = "../conf/access/users_allow.list"
# file with blocked IP-address ranges for regular users;
# empty path means that no such rules are formed;
user_block_list = "../conf/access/users_block.list"
# whether the disallowed IP address is stated to regular users
# when it happens that user IP address is not allowed;
user_show_blocked_ip = true
# option whether guest users are allowed by default
guest_default_allow = true
# file with allowed IP-address ranges for guest users;
# empty path means that no such rules are formed;
guest_allow_list = "../conf/access/guests_allow.list"
# file with blocked IP-address ranges for guest users;
# empty path means that no such rules are formed;
guest_block_list = "../conf/access/guests_block.list"
# whether the disallowed IP address is stated to guest users
# when it happens that user IP address is not allowed;
guest_show_blocked_ip = true

[view]
# the path at which the arxifter web is served;
# set it to "" if arxifter is served at the "/" path
path_prefix = "/biorxiv"
# the page shown to users has two versions:
# with common JS libs served from CDN vs. locally
# main_page = "../view/page_local.html"
main_page = "../view/page_cdn.html"
# where the statically served files are located
static_dir = "../view/static/"

[backlink]
# to be set according to actual deployments;
# the top-left link: it can be customized;
name = "arχifter"
link = "https://arxifter.quadet.com"
title = "to arχifter home page"

[notices]
# the text at the top of the user-popup
note_users = "about.txt"
# whether the note_users file should be rendered as html;
# if not, it is rendered as plain text
note_users_html = false

[ui]
# a technical part that can be left unchanged;
# for cookie that keeps user id if users ask for it
user_id = "arxifter.userid"
# how many days that cookie should be kept;
# it gets auto-renewed if user visits arxifter meanwhile
retain_user = 30
# name prefix for items stored at browser local storage
storage_prefix = "arxifter.biorxiv"
# how many sifts can get stored in browser local storage;
# the sifts are stored by default, but users can disallow it;
# since browsers have a limited capacity for data storage,
# this value should not be set too large;
recall_sifts = 20

[feeds]
# deployments can be used for a subset of feeds only;
# and combined subjects can be specified for feeds too;
subjects = "subjects.txt"
default_subject = "cell_biology"
# to allow users to make queries with subject combinations
# differing from the listed ones in the "subjects" file;
# it still has to be with subjects listed there at first;
allow_combinations = true

[data]
# where the feeds and the data based on them are stored;
storage_dir = "../feed/"
# whether past stored feed data should be removed;
pruning = true
# how long the feeds should be retained;
# (this value is used only when pruning is set to true)
kept_days = 7
# the depo part of ingested data
depo_depth = 30
depo_renew = 2

[libs]
# directory with a version of hnswlib that has knn searches
# with support for returning unique docs;
# arxifter uses a patched hnswlib for sentence-wise searches;
hnswlib = "../libs/hnswlib/"

[embed]
# models from HF are expected to be stored at "hub" subdirectory
# of the directory set to the "models_base_dir" key
models_base_dir = "../mods/"
# model for dense encoders
# (in the way it is taken by the fastembed library);
# if the "dense_embed_model" is not within the models recognized
# by the fastembed library, the respective HF directory
# has to contain info.toml file with model specification;
dense_embed_model = "BAAI/bge-base-en-v1.5"
dense_embed_dim = 768
# dense_embed_model = "local/neuml-pubmedbert-base-embeddings-fp16"
# dense_embed_dim = 768
# model for static encoders
# (in the way it is taken by the model2vec library)
static_embed_model = "NeuML/pubmedbert-base-embeddings-8M"
static_embed_dim = 256

[sifting]
# presifting part done by the used dense embedding model
pick_count_dense = 5
# presifting part done by the used static embedding model
pick_count_static = 5
# the maximal count of articles that LLM ought to provide
answer_max_count = 5

[prompts]
# the prompt parts that are used for LLM querying
explained = "prompts/explained.txt"
common_end = "prompts/ending.txt"

[llms]
# LLM inference API end point for OpenAI compatible services;
# empty "base_url" means that OpenAI is used;
# so far OpenAI and Fireworks AI have been tested;
# "model_name" model used by the inferring LLM;
# "asking_form" is "responses" or "completions"
# Fireworks AI:
# base_url = "https://api.fireworks.ai/inference/v1"
# model_name = "fireworks/gpt-oss-20b"
# asking_form = "responses"
# OpenAI:
base_url = ""
model_name = "gpt-5-nano"
asking_form = "responses"

[users]
# if a deployment is to be w/o allowing guests,
# the "with_guest" value has to be set to false
with_guest = true
# session span (in hours) of guest users
guest_span = 24
# where ids of regular and guest users are stored;
# users are set by ids only (i.e. not by name/password pairs);
regular_users = "../keys/users.list"
guest_ids = "../keys/guest/"

[keys]
# locations of LLM api keys;
regular_users = "../keys/users/"
guest_user = "../keys/guest.key"

[mocking]
# for development purposes
answers_dir = "../conf/mocking/"
mocking_delay = 4
to_mock = false

[debugging]
# for testing purposes
query_sifting = false
feed_ingest = false
